name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Linter stuff
        run: |
          pip3 install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source
      - name: Run ptests
        run: |
          pip3 install pytest
          pytest tests/all_tests.py

